Goal 1 - Error 2: Routes - NameError: undefined local variable or method 'root_path' for #<RSpec::ExampleGroups::GuestVisitsHomepage::LandingPage:0x007fb64fc45740> - This error is occurring because no routes have been defined. - To solve this error, we create new routes.